[ Refactoring ] using just default config file, removing --config-file
maxbube/mydumper pull request #479
Opened 2021-11-08 18:22 UTC by davidducos

2021-11-16 14:36 UTC, maxbube requested changes
This is a breaking change, I guess we must first support both and print a deprecation message to not break actual deployments

2021-11-16 14:44 UTC, davidducos commented
@maxbube --config was added on v0.11.1 and as we are still on v0, I think that we can avoid formal deprecation messages, as we are planning to implement since release v1. What do you think?

2021-11-22 17:29 UTC, maxbube submitted a review, later dismissed

2021-11-26 15:22 UTC, maxbube approved these changes

2021-11-28 18:24 UTC, merged